Repository mp-co-ru/mpc-peresvet, pull requests merged in 2023-12, with the labels that each got.

#196 F 195 correct debug
  .vscode/launch.json
  README.md
  docker/compose/.env
  docker/compose/docker-compose.alerts.debug.yml
  docker/compose/docker-compose.dataStorages.all.debug.yml
  docker/docker-files/common/Dockerfile.common.nginx.unit
  docker/docker-files/common/debug_create_launch.py
  docker/docker-files/common/debug_setup.py
  docker/docker-files/common/run_debug_setup.sh
  docker/docker-files/dataStorages/Dockerfile.dataStorages.all.debug
  pics/vscode_debug.png
  run.sh
  run_debug.sh
  tests/load/get_history_test/locustfile_get_history_data_prs-psql.py
  tests/load/get_history_test/locustfile_ws_get_history_data_prs-psql.py
  tests/load/get_test/locustfile_get_data_prs-psql.py
  tests/load/get_test/locustfile_ws_get_data_prs-psql.py
  tests/load/set_test/locustfile_set_data_prs-psql.py
  tests/load/set_test/locustfile_ws_set_data_prs-psql.py
Labels: enhancement

#170 F 169 add grafana plugin docs
  docker/compose/docker-compose.alerts.all.yml
  docker/compose/docker-compose.connectors.all.yml
  docker/compose/docker-compose.dataStorages.all.yml
  docker/compose/docker-compose.methods.all.yml
  docker/compose/docker-compose.objects.all.yml
  docker/compose/docker-compose.schedules.all.yml
  docker/compose/docker-compose.tags.all.yml
  docker/debug/compose/docker-compose.tags_api_crud.debug.yml
  docker/debug/compose/docker-compose.tags_api_crud.uvicorn.yml
  docker/debug/compose/docker-compose.tags_model_crud.debug.yml
  docker/debug/compose/docker-compose.tags_model_crud.uvicorn.yml
  docker/debug/debug_create_launch.py
  docker/debug/debug_setup.py
  docker/debug/docker-files/tags_api_crud/Dockerfile.tags_api_crud.debug
  docker/debug/docker-files/tags_model_crud/Dockerfile.tags_model_crud.debug
  docker/debug/run_tags_api_crud_debug.sh
  docker/debug/run_tags_model_crud_debug.sh
  docs/source/grafana/grafana_integration.rst
  docs/source/grafana/grafana_plugin.rst
  docs/source/index.rst
  docs/source/installation.rst
  docs/source/pics/grafana_plugin_enter_value.png
  docs/source/pics/grafana_plugin_field_var.png
  docs/source/pics/grafana_plugin_icon_var.png
  docs/source/pics/grafana_plugin_option_01.png
  docs/source/pics/grafana_plugin_option_03.png
  docs/source/pics/grafana_plugin_update_interval.png
  docs/source/pics/grafana_setup_add_dashboard.png
  docs/source/pics/grafana_setup_add_datasource.png
  docs/source/pics/grafana_setup_add_panel.png
  docs/source/pics/grafana_setup_conf_datasource.png
  docs/source/pics/grafana_setup_conf_panel.png
  docs/source/pics/grafana_setup_install_mqtt.png
  docs/source/pics/grafana_setup_plugins_add_new_ds.png
  docs/source/pics/grafana_setup_plugins_menu.png
  docs/source/pics/grafana_setup_search_plugin.png
  docs/source/pics/grafana_setup_turn_off_refresh.png
  run_debug.sh
Labels: documentation

#184 #183 Fixed
  src/services/retranslator/app/retranslator_app_svc.py
Labels: bug

#200 #199 Fixed
  src/common/api_crud_svc.py
  src/services/connectors/api_crud/connectors_api_crud_svc.py
  src/services/dataStorages/api_crud/dataStorages_api_crud_svc.py
  src/services/objects/api_crud/objects_api_crud_svc.py
  src/services/tags/api_crud/tags_api_crud_svc.py
Labels: bug

#208 F 190 add nginx
  .gitignore
  README.md
  config/nginx/nginx.conf
  config/nginx/no_ssl/default.conf.no_ssl.template
  config/nginx/no_ssl/default.conf.template
  config/nginx/peresvet/locations/peresvet.locations.conf.template
  config/nginx/peresvet/locations/platform.conf
  config/nginx/peresvet/upstreams/objects.conf
  config/nginx/peresvet/upstreams/peresvet.upstreams.conf.template
  config/nginx/peresvet/upstreams/tags.conf
  config/nginx/ssl/default.conf.ssl.template
  docker/compose/.cont_all_in_one.env
  docker/compose/.env
  docker/compose/docker-compose.alerts.all.yml
  docker/compose/docker-compose.connectors.all.yml
  docker/compose/docker-compose.dataStorages.all.yml
  docker/compose/docker-compose.methods.all.yml
  docker/compose/docker-compose.nginx.yml
  docker/compose/docker-compose.objects.all.yml
  docker/compose/docker-compose.retranslator.yml
  docker/compose/docker-compose.schedules.all.yml
  docker/compose/docker-compose.tags.all.yml
  docker/docker-files/alerts/Dockerfile.alerts.all
  docker/docker-files/alerts/Dockerfile.alerts.load_tests
  docker/docker-files/alerts/Dockerfile.alerts.prepare_load_tests
  docker/docker-files/alerts/config_nginx.unit_alerts.all.json
  docker/docker-files/connectors/Dockerfile.connectors.all
  docker/docker-files/connectors/config_nginx.unit_connectors.all.json
  docker/docker-files/dataStorages/Dockerfile.dataStorages.all
  docker/docker-files/dataStorages/Dockerfile.dataStorages.prepare_load_tests
  docker/docker-files/dataStorages/config_nginx.unit_dataStorages.all.json
  docker/docker-files/methods/Dockerfile.methods.all
  docker/docker-files/methods/Dockerfile.methods.load_tests
  docker/docker-files/methods/config_nginx.unit_methods.all.json
  docker/docker-files/nginx/Dockerfile.nginx
  docker/docker-files/objects/Dockerfile.objects.all
  docker/docker-files/objects/config_nginx.unit_objects.all.json
  docker/docker-files/retranslator/Dockerfile.retranslator
  docker/docker-files/schedules/Dockerfile.schedules.all
  docker/docker-files/schedules/config_nginx.unit_schedules.all.json
  docker/docker-files/tags/Dockerfile.tags.all
  docker/docker-files/tags/Dockerfile.tags.prepare_load_tests
  run.sh
  src/services/alerts/app_api/alerts_app_api_svc.py
  src/services/connectors/api_crud/Pipfile
  src/services/connectors/api_crud/connectors_api_crud_svc.py
  src/services/connectors/app/Pipfile
  src/services/objects/api_crud/objects_api_crud_svc.py
  src/services/retranslator/app/retranslator_app_svc.py
Labels: enhancement

#218 #211 Fixed
  src/services/connectors/app/connectors_app_svc.py
Labels: bug
